version: '3'

services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ../target/core-java-websocket-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/websocket.war
    environment:
      - CATALINA_OPTS=-Xmx512m
    restart: always
